### ISSUE TITLE
line 44-47 comments

### ISSUE THREAD

**Issue by yekong90** [thimoonxy/subnetting#1]
line 44-47 comments
those situation is not valid netmask value, mask must be continiuing 1.

def mask2cidr(mask='255.255.255.0'):
    '''
    1.  '255.11111.266.4' to '255.255.255.0' to 24
    2.  '255.128.255.0'  to 9
    '''

this part is not right.

those are not valid mask, it 9 equals 255.128.0.0 but not 255.128.255.0, for 255.11111.266.4 you should treat this input is illegal.

**Comment by thimoonxy** [comment]
Hey yekong,

Thanks for your question, but I thought you might misunderstood func mask2cidr.

It's used for correcting wrong masks, for instance, if you have ever manage iptables stuffs, you'll find that if you put some invalid masks in your restore file, the iptables-restore just correct them automaticly.

Yeah, those 2x examples are invalid masks. If you have chance to use this sub-func as any web-app module/func you'd find it's a bit useful when someone inputs a wrong mask, the app is able to auto-correct the typo on the site-tool rather than raising an ugly error.

In this case, I don't see it runs with any problem yet.

In [1]: from subnetting import *

In [2]: mask2cidr('255.1111.266.4')
Out[2]: 24

In [3]: mask2cidr('255.128.255.0')
Out[3]: 9

Thanks,
Simon
